import Image from "next/image";
import { Button, Cards, Checklist, CTA } from "@/components/site-shell";
import { MapLoader } from "@/components/map-loader";
import { bodyTypes, benefits, process, projects } from "@/data/content";
import { company, siteUrl, whatsappHref } from "@/data/company";
import { images } from "@/data/site-images";

export default function Home() {
  const schema = { "@context": "https://schema.org", "@type": "LocalBusiness", "@id": `${siteUrl}/#business`, name: company.name, url: siteUrl, foundingDate: "2015", telephone: company.phoneE164, address: { "@type": "PostalAddress", streetAddress: company.address.street, addressLocality: company.address.commune, addressRegion: company.address.region, postalCode: company.address.postalCode, addressCountry: "CL" }, areaServed: { "@type": "Country", name: "Chile" }, hasMap: company.mapsUrl };
  return <><script type="application/ld+json" dangerouslySetInnerHTML={{ __html: JSON.stringify(schema) }} />
    <section className="hero"><Image src={images.hero.src} alt={images.hero.alt} fill priority sizes="100vw" /><div className="hero-overlay" /><div className="container hero-content"><p className="eyebrow">Fabricación y mantención de carrocerías en Chile</p><h1>Carrocerías para camiones diseñadas para su operación</h1><p>Fabricamos, montamos y mantenemos carrocerías para carga general y transporte refrigerado. Desarrollamos soluciones adaptadas al tipo de carga, al chasis y a las exigencias de cada empresa.</p><div className="hero-actions"><Button href="/cotizar">Solicitar cotización</Button><a className="button button-secondary" href={whatsappHref()} target="_blank" rel="noreferrer">Hablar por WhatsApp</a></div><span className="hero-proof">Más de 10 años atendiendo a empresas de transporte en Chile.</span></div></section>
    <section className="section"><div className="container split"><div><p className="eyebrow">HDC-Tiberi</p><h2>Soluciones de carrozado para empresas de transporte</h2></div><p className="lead">Ayudamos a transformar un chasis en una herramienta de trabajo preparada para operar. Contamos con fabricación propia, soluciones importadas desde Brasil y experiencia en proyectos para carga general, distribución y transporte en frío.</p></div></section>
    <section className="section muted"><div className="container"><div className="section-heading"><p className="eyebrow">Nuestras líneas</p><h2>Una solución para cada operación</h2></div><Cards items={bodyTypes} /></div></section>
    <section className="section"><div className="container split"><div><p className="eyebrow">Por qué trabajar con nosotros</p><h2>Un proyecto pensado para trabajar</h2><p>Evaluamos las condiciones reales de su operación para orientar una solución útil y sostenible en el tiempo.</p></div><Checklist items={benefits} /></div></section>
    <section className="section dark"><div className="container"><p className="eyebrow">Nuestro proceso</p><h2>¿Cómo desarrollamos una carrocería?</h2><div className="steps">{process.map((item, index) => <div key={item}><span>0{index + 1}</span><h3>{item}</h3><p>{["Revisamos carga, vehículo, dimensiones y uso.", "Proponemos configuración y elementos necesarios.", "Fabricamos o seleccionamos una alternativa importada.", "Montamos y revisamos terminaciones antes de entregar."][index]}</p></div>)}</div></div></section>
    <section className="section"><div className="container"><div className="section-heading"><p className="eyebrow">Proyectos realizados</p><h2>Carrocerías desarrolladas para operaciones reales</h2><p>Conozca algunas configuraciones de carga, distribución, montaje y transporte especializado.</p></div><div className="project-grid">{projects.map((project) => <article className="project-tile project-tile-photo" key={project.src}><Image src={project.src} alt={project.alt} width={project.width} height={project.height} sizes="(max-width: 850px) 100vw, (max-width: 1100px) 50vw, 33vw"/><div className="project-tile-copy"><span>{project.text}</span><strong>{project.title}</strong></div></article>)}</div><Button href="/proyectos" secondary>Ver proyectos</Button></div></section>
    <section className="section muted"><div className="container contact-band"><div><p className="eyebrow">Ubicación</p><h2>Atención en Santiago para proyectos en Chile</h2><p>Nuestra planta está ubicada en Renca, Región Metropolitana. Desde aquí atendemos proyectos para empresas de transporte y propietarios de camiones.</p></div><div className="location-block"><address><strong>{company.address.street}</strong><span>{company.address.commune}, {company.address.region}</span><a href={`tel:${company.phoneE164}`}>{company.phoneDisplay}</a><a href={company.mapsUrl} target="_blank" rel="noreferrer">Abrir en Google Maps</a></address><MapLoader compact /></div></div></section><CTA />
  </>;
}
