import Link from "next/link";
import type { ReactNode } from "react";
import { ArrowRight, Check, Menu, MessageCircle, Phone } from "lucide-react";
import { company, whatsappHref } from "@/data/company";

const nav = [{href:"/carrocerias", label:"Carrocerías"},{href:"/servicios",label:"Servicios"},{href:"/transporte-en-frio",label:"Transporte en frío"},{href:"/proyectos",label:"Proyectos"},{href:"/nosotros",label:"Nosotros"},{href:"/blog",label:"Blog"},{href:"/contacto",label:"Contacto"}];
export function Button({ href, children, secondary = false }: {href:string; children:ReactNode; secondary?:boolean}) { return <Link className={`button ${secondary ? "button-secondary" : ""}`} href={href}>{children}<ArrowRight size={17}/></Link>; }
export function Header() { return <header className="header"><div className="container topbar"><span>Fabricación, montaje y mantención en Chile</span><a href={`tel:${company.phoneE164}`}><Phone size={14}/>{company.phoneDisplay}</a></div><div className="container nav"><Link href="/" className="logo"><strong>HDC</strong><span>TIBERI<br/><small>CARROCERÍAS</small></span></Link><nav aria-label="Navegación principal">{nav.map(i=><Link href={i.href} key={i.href}>{i.label}</Link>)}</nav><Link className="quote-link" href="/cotizar">Solicitar cotización</Link><details className="mobile-menu"><summary aria-label="Abrir menú"><Menu size={22}/></summary><div>{nav.map(i=><Link href={i.href} key={i.href}>{i.label}</Link>)}<Link className="mobile-quote" href="/cotizar">Solicitar cotización</Link></div></details></div></header>; }
export function Footer() { return <footer className="footer"><div className="container footer-grid"><div><Link href="/" className="logo logo-light"><strong>HDC</strong><span>TIBERI<br/><small>CARROCERÍAS</small></span></Link><p>Fabricación, montaje, reparación y mantención de carrocerías para camiones.</p></div><div><h3>Soluciones</h3><Link href="/carrocerias/carga-general">Carga general</Link><Link href="/carrocerias/refrigeradas">Carrocerías refrigeradas</Link><Link href="/servicios">Servicios</Link></div><div><h3>Contacto</h3><a href={`tel:${company.phoneE164}`}>{company.phoneDisplay}</a><a href={company.mapsUrl} target="_blank" rel="noreferrer">{company.address.street}, {company.address.commune}</a><Link href="/cotizar">Solicitar cotización</Link></div></div><div className="container footer-bottom"><span>© {new Date().getFullYear()} Carrocerías HDC-Tiberi.</span><span><Link href="/terminos-y-condiciones">Términos</Link><Link href="/politica-de-privacidad">Privacidad</Link><Link href="/politica-de-cookies">Cookies</Link></span></div></footer>; }
export function WhatsApp() { return <a className="whatsapp" href={whatsappHref()} target="_blank" rel="noopener noreferrer" aria-label="Hablar por WhatsApp"><MessageCircle size={24}/></a>; }
export function PageHero({ eyebrow, title, text }: {eyebrow:string; title:string; text:string}) { return <section className="page-hero"><div className="container"><p className="eyebrow">{eyebrow}</p><h1>{title}</h1><p>{text}</p></div></section>; }
export function Cards({items}:{items:{title:string;text:string;href:string}[]}) { return <div className="card-grid">{items.map(item=><article className="card" key={item.href}><span className="card-mark"/><h3>{item.title}</h3><p>{item.text}</p><Link href={item.href}>Conocer más <ArrowRight size={16}/></Link></article>)}</div>; }
export function Checklist({items}:{items:string[]}) { return <ul className="checklist">{items.map(i=><li key={i}><Check size={18}/>{i}</li>)}</ul>; }
export function CTA() { return <section className="cta"><div className="container cta-inner"><div><p className="eyebrow">Hablemos de su operación</p><h2>Cuéntenos qué necesita transportar</h2><p>Indíquenos el modelo del camión, el tipo de carga y las características generales del proyecto.</p></div><div><Button href="/cotizar">Solicitar cotización</Button><a className="text-link" href={whatsappHref()} target="_blank" rel="noreferrer">Consultar por WhatsApp</a></div></div></section>; }
export function FAQ({items}:{items:string[][]}) { return <div className="faq">{items.map(([q,a])=><details key={q}><summary>{q}</summary><p>{a}</p></details>)}</div>; }
