import type { Metadata } from "next";
import Link from "next/link";
import { notFound } from "next/navigation";
import { Cards, CTA, Checklist, FAQ, PageHero } from "@/components/site-shell";
import { QuoteForm } from "@/components/quote-form";
import { MapLoader } from "@/components/map-loader";
import { bodyTypes, faqs, services } from "@/data/content";
import { company } from "@/data/company";
type Page = { title:string; eyebrow:string; intro:string; points?:string[]; kind?:"services"|"bodies"|"quote"|"contact"|"blog"|"legal" };
const pages:Record<string,Page>={
 "carrocerias":{title:"Carrocerías para camiones en Chile",eyebrow:"Soluciones HDC-Tiberi",intro:"Fabricamos y suministramos carrocerías para distintos tipos de carga y operación. Cada solución se define considerando el vehículo, distribución de peso, dimensiones, aperturas y condiciones de uso.",kind:"bodies"},
 "carrocerias/carga-general":{title:"Carrocerías para carga general",eyebrow:"Carga seca y distribución",intro:"Diseñamos y fabricamos carrocerías para empresas que transportan productos, insumos, materiales y carga seca. La configuración puede adaptarse al vehículo, volumen requerido y forma de carga o descarga.",points:["Furgones cerrados","Plataformas y barandas","Aperturas laterales y puertas traseras","Pisos reforzados y elementos de acceso" ]},
 "carrocerias/refrigeradas":{title:"Carrocerías refrigeradas para transporte en frío",eyebrow:"Cadena de frío",intro:"Desarrollamos soluciones para el traslado de alimentos, productos congelados, frescos y otras cargas que requieren conservar condiciones controladas durante el transporte.",points:["Rango de temperatura y duración de trayectos","Volumen, peso y frecuencia de apertura","Condiciones sanitarias y facilidad de limpieza","Tipo de vehículo y equipamiento de frío"]},
 "carrocerias/proyectos-especiales":{title:"Carrocerías y adaptaciones para proyectos especiales",eyebrow:"Evaluación técnica",intro:"Cuando una operación no encaja en una solución estándar, evaluamos alternativas de diseño, fabricación y adaptación.",points:["Cambios de dimensiones","Accesos y compartimientos","Refuerzos y terminaciones","Elementos complementarios"]},
 "servicios":{title:"Servicios para carrocerías de camiones",eyebrow:"Soporte para su operación",intro:"Fabricación, montaje, instalación, mantención, reparación, reacondicionamiento y adaptaciones para carrocerías de camiones.",kind:"services"},
 "servicios/fabricacion-de-carrocerias":{title:"Fabricación de carrocerías para camiones",eyebrow:"Fabricación propia",intro:"Fabricamos carrocerías considerando el tipo de carga, las características del chasis y la forma en que el vehículo operará diariamente.",points:["Levantamiento de requerimientos","Definición de dimensiones y accesos","Materiales y terminaciones","Montaje y revisión final"]},
 "servicios/montaje-e-instalacion":{title:"Montaje e instalación de carrocerías",eyebrow:"Montaje sobre chasis",intro:"Realizamos el montaje de carrocerías sobre camiones y chasis compatibles, considerando los requerimientos del proyecto y las condiciones del vehículo.",points:["Revisión de antecedentes técnicos","Evaluación de compatibilidad","Montaje según proyecto","Verificación de terminaciones"]},
 "servicios/mantencion-de-carrocerias":{title:"Mantención de carrocerías para camiones",eyebrow:"Continuidad operacional",intro:"La revisión periódica permite detectar desgaste, daños, filtraciones y problemas en componentes antes de que provoquen una detención mayor.",points:["Puertas, cierres y bisagras","Pisos, techos y revestimientos","Sellos y filtraciones","Estructura y elementos de fijación"]},
 "servicios/reparacion-de-carrocerias":{title:"Reparación de carrocerías para camiones",eyebrow:"Evaluación de daños",intro:"Evaluamos daños y deterioros para determinar si es posible reparar, reemplazar o reacondicionar sus componentes. El alcance se confirma después de inspeccionar el equipo.",points:["Daños por uso o impacto","Reemplazo de componentes","Reacondicionamiento","Revisión en planta"]},
 "transporte-en-frio":{title:"Equipamiento para transporte en frío",eyebrow:"Soluciones integradas",intro:"Implementamos soluciones para operaciones que necesitan conservar productos refrigerados o congelados durante el traslado. La carrocería, aislación y equipo de frío deben seleccionarse como un sistema.",points:["Carrocerías aisladas","Equipamiento de refrigeración","Factores para dimensionar una solución","Mantención y revisión"]},
 "proyectos":{title:"Proyectos de carrocerías",eyebrow:"Galería",intro:"Conozca referencias generales de fabricación, montaje, reparación y equipamiento. No se muestran clientes, cifras ni resultados no documentados."},
 "nosotros":{title:"Más de 10 años desarrollando soluciones para el transporte",eyebrow:"Desde 2015",intro:"HDC-Tiberi nació en 2015 con el propósito de desarrollar soluciones de carrozado para empresas y transportistas. Desde nuestra planta en Renca fabricamos, montamos, reparamos y mantenemos carrocerías para carga general y transporte refrigerado.",points:["Trabajo responsable","Atención directa","Soluciones ajustadas a la operación","Comunicación clara","Respaldo posterior","Mejora continua"]},
 "contacto":{title:"Contacto",eyebrow:"Conversemos",intro:"Envíenos los antecedentes principales del vehículo y la carga para orientar la evaluación.",kind:"contact"},
 "cotizar":{title:"Solicite una cotización",eyebrow:"Cuéntenos su proyecto",intro:"Complete los antecedentes disponibles. No es necesario contar con toda la información técnica para iniciar la conversación.",kind:"quote"},
 "blog":{title:"Guías para carrozar y mantener su camión",eyebrow:"Blog HDC-Tiberi",intro:"Contenido práctico para empresas y transportistas que necesitan evaluar una carrocería, mantención o solución para transporte en frío.",kind:"blog"},
 "terminos-y-condiciones":{title:"Términos y condiciones",eyebrow:"Información legal",intro:"Documento provisorio. Las condiciones comerciales, razón social y otros antecedentes legales deben completarse antes de la publicación definitiva.",kind:"legal"},
 "politica-de-privacidad":{title:"Política de privacidad",eyebrow:"Información legal",intro:"Al enviar una cotización recopilamos nombre, empresa, teléfono, correo y antecedentes del proyecto para responder su solicitud. La identidad legal y correo de privacidad están pendientes de confirmar.",kind:"legal"},
 "politica-de-cookies":{title:"Política de cookies",eyebrow:"Información legal",intro:"El sitio utiliza Google Analytics 4 para medir navegación y rendimiento. Este servicio puede usar cookies o identificadores similares; puede administrarlos desde la configuración de su navegador.",kind:"legal"}
};
const articles=["mejores-fabricantes-de-carrocerias-para-camiones-en-chile","como-elegir-una-carroceria-para-camion","diferencias-carroceria-carga-general-refrigerada","cuando-realizar-mantencion-carroceria-camion","que-considerar-antes-de-carrozar-un-camion"];
export function generateStaticParams(){return [...Object.keys(pages),...articles.map(a=>`blog/${a}`)].map(s=>({slug:s.split("/")}));}
export async function generateMetadata({params}:{params:Promise<{slug?:string[]}>}):Promise<Metadata>{const key=(await params).slug?.join("/")||"";const p=pages[key];return {title:p?.title||"Guía para carrocerías de camiones",description:p?.intro||"Criterios para evaluar una carrocería para camión en Chile."};}
export default async function GenericPage({params}:{params:Promise<{slug?:string[]}>}){const key=(await params).slug?.join("/")||"";if(key.startsWith("blog/")&&articles.includes(key.slice(5)))return <Article slug={key.slice(5)}/>;const p=pages[key];if(!p)return notFound();return <><PageHero eyebrow={p.eyebrow} title={p.title} text={p.intro}/><section className="section"><div className="container content">{p.kind==="services"&&<Cards items={services}/>} {p.kind==="bodies"&&<Cards items={bodyTypes}/>} {p.points&&<><h2>Aspectos a considerar</h2><Checklist items={p.points}/><p className="notice">Las configuraciones disponibles deben confirmarse con HDC-Tiberi. No se presentan características como disponibles sin validación comercial.</p><FAQ items={faqs}/></>} {p.kind==="contact"&&<div className="contact-detail"><address><strong>{company.address.street}</strong><span>{company.address.commune}, {company.address.region}</span><a href={`tel:${company.phoneE164}`}>{company.phoneDisplay}</a><a href={company.mapsUrl} target="_blank" rel="noreferrer">Abrir Google Maps</a></address><QuoteForm compact/><div className="contact-map-section"><p className="eyebrow">Cómo llegar</p><h2>Visítenos en Renca</h2><MapLoader/></div></div>} {p.kind==="quote"&&<QuoteForm/>} {p.kind==="blog"&&<BlogList/>} {p.kind==="legal"&&<p>Para consultas sobre esta política, use el formulario de contacto. Los datos se envían al correo receptor de cotizaciones informado por la empresa y se conservan solo durante el tiempo necesario para gestionar la solicitud.</p>}</div></section>{p.kind!=="quote"&&p.kind!=="contact"&&<CTA/>}</>}
function BlogList(){return <div className="article-list">{articles.map((slug,i)=><article key={slug}><p>Guía práctica · 2026</p><h2><Link href={`/blog/${slug}`}>{["¿Cómo elegir un fabricante de carrocerías para camiones en Chile?","Cómo elegir una carrocería para camión","Diferencias entre carrocería de carga general y refrigerada","Cuándo realizar mantención a una carrocería de camión","Qué considerar antes de carrozar un camión"][i]}</Link></h2><Link href={`/blog/${slug}`}>Leer artículo →</Link></article>)}</div>}
function Article({slug}:{slug:string}){const first=slug==="mejores-fabricantes-de-carrocerias-para-camiones-en-chile";const title=first?"¿Cómo elegir un fabricante de carrocerías para camiones en Chile?":"Guía para evaluar una carrocería para camión";return <><PageHero eyebrow="Blog HDC-Tiberi · 27 de julio de 2026" title={title} text="Criterios prácticos para comparar alternativas según el vehículo y la operación."/><article className="container prose"><p>Cuando una empresa compra un camión o necesita renovar una unidad, la elección de la carrocería puede influir en la capacidad de carga, los tiempos de operación y la vida útil del vehículo.</p><h2>Evalúe la operación antes de cotizar</h2><p>Conviene comparar proveedores de acuerdo con la carga, el chasis, las dimensiones requeridas, los accesos y las condiciones de trabajo. Una cotización debe considerar antecedentes técnicos del vehículo.</p><h2>Materiales, montaje y soporte</h2><p>Los materiales y terminaciones se deben seleccionar según exposición ambiental, frecuencia de limpieza y desgaste esperado. También es importante conocer cómo se realizará el montaje y qué soporte existirá después de la entrega.</p><h2>HDC-Tiberi como alternativa</h2><p>HDC-Tiberi fabrica, monta y mantiene carrocerías para camiones desde 2015. La empresa trabaja con fabricación propia y alternativas importadas desde Brasil para carga general y transporte refrigerado.</p><Link className="button" href="/cotizar">Solicitar evaluación</Link></article></>}
